### ISSUE TITLE
Implement draft data model

### ISSUE THREAD

**Issue by hangler** [bcgov/ExitSurveyAdmin#24]
Per #5, implement the draft data models in code.

- [x] Add AdminUser: [docs](https://github.com/bcgov/ExitSurveyAdmin/wiki/Data-model#adminuser)
- [x] Add Employee: [docs](https://github.com/bcgov/ExitSurveyAdmin/wiki/Data-model#employee), issue #26
- [x] Add EmployeeStatusEnum: [docs](https://github.com/bcgov/ExitSurveyAdmin/wiki/Data-model#employeestatusenumeration), issue #27
- [x] Add EmployeeTimelineEntry: [docs](https://github.com/bcgov/ExitSurveyAdmin/wiki/Data-model#employeetimelineentry), issue #28 
- [x] Add EmployeeActionTypeEnum: [docs](https://github.com/bcgov/ExitSurveyAdmin/wiki/Data-model#employeeactiontypeenumeration), issue #29 
- [x] Add TaskLogEntry: [docs](https://github.com/bcgov/ExitSurveyAdmin/wiki/Data-model#taskoutcomeenumeration), issue #30 
- [x] Add TaskTypeEnum: [docs](https://github.com/bcgov/ExitSurveyAdmin/wiki/Data-model#tasktypeenumeration), issue #31 
- [x] Add TaskOutcomeEnum: [docs](https://github.com/bcgov/ExitSurveyAdmin/wiki/Data-model#taskoutcomeenumeration), issue #32
